### ISSUE TITLE
Expose disabling logging to the Python interface

### ISSUE THREAD

**Issue by dhdaines** [ReadAlongs/SoundSwallower#16]
As stated above!

**Comment by dhdaines** [comment]
Fixed in https://github.com/ReadAlongs/SoundSwallower/commit/63a2dd8cf43b94d992292ef50b18887394bfc225

**Comment by lenzo-duo** [comment]
This is a really nice quality of life add. Also - I never expected my goforward sample to be useful for 20 years!
