### ISSUE TITLE
Consider adding a requirements.txt containing scikit-build

### ISSUE THREAD

**Issue by lenzo-duo** [ReadAlongs/SoundSwallower#19]
A `requirements.txt` with `scikit-build` it in is all that's needed to populate the venv with everything it needs

**Comment by dhdaines** [comment]
Hi! This is handled by the pyproject.toml at the moment, which works for pip but not for other things... I am always deeply confused by the multiple ways in which one could specify build dependencies in Python, but I think this can't hurt to add, so I've added it.

**Comment by lenzo-duo** [comment]
I was using setup.py develop in the repo... this will probably make things easier and be harmless! Thank you
