### ISSUE TITLE
feature request: two pass phonetic alignment

### ISSUE THREAD

**Issue by lenzo-ka** [ReadAlongs/SoundSwallower#20]
It would be great to be able to easily get both word and phonetic timings/alignments -- perhaps as a two pass process, first to get which pronunciations and word timings, and then a second pass for phone timings. In general, it would be great to get phonetic alignments, but getting word AND phonetic alignments with some sort of sensible relationship would be superb.

We've done some of this by doing a second pass the pronunciation, using "phoneme words" with single-phone pronunciations, but that doesn't account for word-phone-position features in the clustering (b, i, m ,s) when using cd models.

Another issue that came up with that approach is that the word boundaries and the phoneme boundary timings didn't align, due to differences in the search. It would be possible to do a phonetic decode within the word boundary, or to adjust to word boundaries after the phonetic pass...

**Comment by dhdaines** [comment]
Yup, this is sort of the same as #9 but I'll leave them both open as it's a priority for the near future!

**Comment by dhdaines** [comment]
Done in #27
