### ISSUE TITLE
Replace some parts of the C code with JavaScript or Python

### ISSUE THREAD

**Issue by dhdaines** [ReadAlongs/SoundSwallower#6]
There are most certainly large parts of the code that just shouldn't be written in C.

An obvious candidate is the JSGF parser, which can be reimplented with Jison http://zaa.ch/jison/ or PEG.js https://pegjs.org/  (yes, as far as I know, there isn't a JSGF parser written in JavaScript already, and yes, despite its name, you can't just parse JSGF as JavaScript)

It would be interesting to reimplement the FSG search as well.  The HMM/GMM implementations would remain in C, obviously.

**Comment by littell** [comment]
If we reimplement the FSG search, maybe that's a good point to allow the integration of an approximate match probability matrix (like we might make from PanPhon), rather than do the approximate phoneme matching discretely in the G2P.  That way, from the user's point of view, they have a FSG recognizer that just supports a large IPA vocabulary, and don't have to worry so much about the details of cross-linguistic mapping.

**Comment by lenzo-duo** [comment]
I am interested in helping with this ^ for approximate match. I have been working on a data driven approach to calculating confusability from the models, rather than from a linguistic feature difference.

**Comment by lenzo-duo** [comment]
As for not being written in C, it is really useful for us to have a C library to link against rather than use js

**Comment by dhdaines** [comment]
Yes, actually going completely to JavaScript is not all that interesting because it also prevents us from using the library from Python or other languages.

I think a better approach is just to reimplement parts that are difficult to interface with other languages - for instance, anything that still uses FILE * simply can't be wrapped with Python and causes lots of headaches with Emscripten as well.

**Comment by dhdaines** [comment]
That said this might be a good justification for the continuing existence of PocketSphinx, which is, after all, a specific C API that is widely used.

**Comment by dhdaines** [comment]
This is done, more or less, in #22
