### ISSUE TITLE
Add pre-compiled wheels for Python 3.11

### ISSUE THREAD

**Issue by joanise** [ReadAlongs/SoundSwallower#60]
I got one e-mail about not being able to install ReadAlongs Studio with Python 3.11 on Windows 11 because the compiler was not installed. lxml and soundswallower were the issues.

It would be nice to include Python 3.12 at the same time if that's feasible already.

**Comment by joanise** [comment]
I can fix lxml by bumping it to 4.9.4, but soundswallower is on us.

**Comment by joanise** [comment]
OK, python 3.12 will be a bigger issue, we can't even build SS with Python 3.12 on Linux at the moment...

**Comment by joanise** [comment]
Split 3.12 into its own issue #61

**Comment by dhdaines** [comment]
Hi, I will fix this shortly, it's two problems:

- Need new version of cibuildwheel
- Need to switch to scikit-build-core

I already fixed both for PocketSphinx so it's pretty simple to do.  Hope to have the time today...

**Comment by dhdaines** [comment]
Fixed in v0.6.4 release

**Comment by joanise** [comment]
Awesome, that's great! Thank you for doing this so quickly.
