### ISSUE TITLE
Change the default branch name to main

### ISSUE THREAD

**Issue by joanise** [ReadAlongs/SoundSwallower#65]
We should follow this change we've done everywhere else, and rename the default branch `main`.

**Comment by joanise** [comment]
@dhdaines Any objections if I do this?

**Comment by dhdaines** [comment]
Nope, go ahead!  It's shorter and easier to type :)

**Comment by joanise** [comment]
And, what I can most about, it will be the same as the other repos so I'll stop getting wrong every time! 😄

**Comment by joanise** [comment]
And I guess you already renamed it. Thanks!
