### ISSUE TITLE
Implement two-pass state alignment and change the alignment search to use it

### ISSUE THREAD

**Issue by dhdaines** [ReadAlongs/SoundSwallower#9]
The alignment search currently doesn't really do the right thing, because it does a state-level alignment only (slow!) and because it doesn't accept silence/noise between words.

This API is fine but it needs to Do What I Mean, which is to do FSG-based "alignment" first then use the resulting coarse alignments to do phone and state level alignments.

**Comment by dhdaines** [comment]
This is part-way done as we removed state alignment :) it is still in the plan to bring back alignment, doing it in this way.

**Comment by lenzo-duo** [comment]
Would this give us word timings + phone timings + state timings? That would be great for doing DNN training

**Comment by dhdaines** [comment]
Yes exactly, I have been meaning to do this for about 10 years now, originally the idea was to use it for MLLR adaptation but we could use it for that too.

**Comment by lenzo-duo** [comment]
Could potentially use the engine for EM and bypass a bunch of SphinxTrain

**Comment by dhdaines** [comment]
Done in #27
